/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Comment: typeof import('./src/components/comment/Comment.vue')['default']
    Comment1: typeof import('./src/components/comment1/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MusicEchart: typeof import('./src/components/music-echart/index.vue')['default']
    NumberTo: typeof import('./src/components/number-to/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Row: typeof import('./src/components/row/index.vue')['default']
    SuyangEchart: typeof import('./src/components/suyang-echart/index.vue')['default']
  }
}
